[env]
TERM = "xterm-256color"

[window]
padding      = { x = 10, y = 10 }
startup_mode = "maximized"

opacity = 0.9

decorations = "Full"
decorations_theme_variant = "Dark"

[scrolling]
history    = 0
multiplier = 0

[font]
normal      = { family = "FiraCode Nerd Font", style = "Medium" }
bold        = { family = "FiraCode Nerd Font", style = "Bold" }
italic      = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "Menlo", style = "Bold Italic" }
size        = 15.0

[colors]
cursor    = { text = "#feffff", cursor =  "#ff00ff" }
selection = { text = "#000000", background = "#c1ddff" }

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#076678"
magenta = "#b16286"
cyan    = "#0aaeb3"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#b16286"
cyan    = "#5ffdff"
white   = "#ebdbb2"

[terminal]
shell = { program = "/opt/homebrew/bin/fish", args = ["--login"] }

